---
# Run Debian-specific tasks
-  import_tasks: debian.yml
   when: ansible_distribution == "Debian" # Doesn't include Ubuntu (ansible_os_family does))

- name: Create web2py user
  command: adduser --system --disabled-password web2py

- name: Create web2py group
  group: name=web2py state=present

- name: Clone Web2py
  git: # recursive by default
    repo: https://github.com/web2py/web2py.git
    dest: /home/setup
    # 2.21.2
    version: 31905858b
    # Don't update unless explicitly desired
    update: no

- name: Configure PyDAL & YATL
  command: git submodule update --init --recursive
  args:
    chdir: /home/setup

- name: Copy routes.py
  template: src=routes.py.j2 dest=/home/setup/routes.py

- name: Clone Coapp
  git: # recursive by default
    repo: https://github.com/sahana/eden-stable
    dest: /home/setup/applications/{{ appname }}
    # Don't update unless explicitly desired
    update: no

- name: Move 000_config.py
  command: cp /home/setup/applications/{{ appname }}/modules/templates/000_config.py /home/setup/applications/{{ appname }}/models

- name: Generate & set hmac_key variable
  set_fact:
    hmac_key: "{{ lookup('password', '/tmp/hmac_key chars=ascii_letters,digits,.-_,,') }}" # Cannot include : or "

- name: Remove hmac_key file
  file: path=/tmp/hmac_key state=absent

- name: Editing 000_config.py
  lineinfile: dest=/home/setup/applications/{{ appname }}/models/000_config.py
              regexp="{{ item.regexp }}"
              backrefs=yes
              line="{{ item.line }}"
              state=present
  loop:
    - { regexp: '^settings.base.template = \"default\"', line: 'settings.base.template = "setup"' }
    - { regexp: '^FINISHED_EDITING_CONFIG_FILE = False', line: 'FINISHED_EDITING_CONFIG_FILE = True' }
    - { regexp: 'akeytochange', line: 'settings.auth.hmac_key = "{{ hmac_key }}"' }
    - { regexp: '^#settings.base.public_url = \"http://127.0.0.1:8000\"', line: 'settings.base.public_url = "http://{{ sitename }}"' }
    - { regexp: '^#settings.base.prepopulate_demo = 0', line: 'settings.base.prepopulate_demo = 0' }

- name: Copy web2py init scripts
  copy: src=web2py dest=/etc/init.d/web2py mode=755

- name: Copy web2py init scripts
  template: src=web2py-scheduler.j2 dest=/etc/init.d/web2py-scheduler mode=755

# - name: update-rc.d
#   command: update-rc.d {{ item }} defaults
#   loop:
#     - web2py
#     - web2py-scheduler

- name: Fix permissions
  file: path=/home/{{item}} state=directory owner=web2py
  loop:
    - setup
    - setup/applications
    - setup/applications/admin/cache
    - setup/applications/admin/cron
    - setup/applications/admin/databases
    - setup/applications/admin/errors
    - setup/applications/admin/sessions
    - setup/applications/{{ appname }}
    - setup/applications/{{ appname }}/cache
    - setup/applications/{{ appname }}/cron
    - setup/applications/{{ appname }}/databases
    - setup/applications/{{ appname }}/errors
    - setup/applications/{{ appname }}/models
    - setup/applications/{{ appname }}/sessions
    - setup/applications/{{ appname }}/static/img/markers
    - setup/applications/{{ appname }}/static/cache
    - setup/applications/{{ appname }}/static/cache/chart
    - setup/applications/{{ appname }}/uploads
    - setup/applications/{{ appname }}/uploads/gis_cache
    - setup/applications/{{ appname }}/uploads/images
    - setup/applications/{{ appname }}/uploads/tracks

- name: Create symlink
  file: src=/home/setup dest=/root/setup state=link

- name: Create symlink (eden in web2py)
  file: src=/home/setup/applications/{{ appname }} dest=/home/setup/eden state=link

- name: Prepopulate Database
  #shell: sudo -H -u web2py python web2py.py -S {{ appname }} -M -R applications/{{ appname }}/static/scripts/tools/noop.py chdir=/home/setup
  command: python web2py.py -S {{ appname }} -M -R applications/{{ appname }}/static/scripts/tools/noop.py chdir=/home/setup
  ignore_errors: yes
  become: yes
  become_user: web2py
  #become_flags: '-H'

- name: Redirect port 80 to 8000
  command: iptables -t nat -A PREROUTING -p tcp --dport 80 -j REDIRECT --to-ports 8000

- name: Launch Coapp
  # https://github.com/ansible/ansible/issues/22171
  #service: name=web2py state=started
  command: /etc/init.d/web2py start

- name: Launch Scheduler
  #service: name=web2py-scheduler state=started
  command: /etc/init.d/web2py-scheduler start
