#!/bin/bash
set -e
if [[ -z "$1" ]]; then
    echo >&2 "Instance needs to be specified: prod, test, demo or setup"
    exit 1
elif [[ ! -d "/home/$1" ]]; then
    echo >&2 "$1 is not a valid instance!"
    exit 1
fi
INSTANCE=$1
#if [ "$INSTANCE" = "setup" ]; then
#    APPNAME=eden_setup
#else
#    APPNAME=eden
#fi
APPNAME=eden
cd /home/$INSTANCE
python web2py.py -S $APPNAME -M